name: GitHub Actions Demo Test Execution

on:
  push:
    branches: [ main ]

jobs:
  build:
    container:
      image: ubuntu:latest
    runs-on: eks_runner
    steps:
      - uses: actions/checkout@v4
      - name: Build with Maven
        run: echo "Sample test Message"