name: GitHub Actions Demo Test Execution

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: echo "Sample test Message"